import { TITLE } from './config';

// The bucketed answers for the PLAY phase (/play), built from the collected
// submissions (kindapointless.csv, 2026-08-08). Each answer is a bucket:
// `votes` = how many people submitted it, `variants` = the distinct wordings
// shown on screen within that one panel.
//
// Rules: the subject WINS by naming any answer only ONE person submitted.
//   - Lose = buckets with 2+ submissions (naming these does NOT win)
//   - Win  = buckets with exactly 1 submission (name any -> everyone drinks)
//
// Within each question the 1-vote answers reveal in array order, so the
// funniest one is placed last as the punchline.

export type Answer = { variants: string[]; votes: number };
export type Question = { text: string; answers: Answer[] };
export type Game = { title: string; questions: Question[] };

export const GAME: Game = {
  title: TITLE,
  questions: [
    {
      text: 'Name a country Pierre has been to',
      answers: [
        { variants: ['Fr*nce', 'France', 'Maybe France?'], votes: 5 },
        { variants: ['Croatia'], votes: 2 },
        { variants: ['Slovenia'], votes: 2 },
        { variants: ['Afghanistan'], votes: 2 },
        { variants: ['That one country with the casino', 'Monaco'], votes: 2 },
        { variants: ['Italy'], votes: 1 },
        { variants: ['Lebanon'], votes: 1 },
        { variants: ['Syria'], votes: 1 },
        { variants: ['Nigeria'], votes: 1 },
        { variants: ['Iran'], votes: 1 },
        { variants: ['New Zealand'], votes: 1 },
        { variants: ['India'], votes: 1 },
        { variants: ['Ireland'], votes: 1 },
        { variants: ['Scotland'], votes: 1 },
        { variants: ['Bulgaria'], votes: 1 },
        { variants: ['England'], votes: 1 },
        { variants: ['Shag Island (South Australia)'], votes: 1 },
        { variants: ['Cock Island, County Mayo'], votes: 1 },
      ],
    },
    {
      text: 'Name one of Pierre’s family members',
      answers: [
        { variants: ['Jean-Luc', 'JL'], votes: 4 },
        { variants: ['Charlie'], votes: 3 },
        { variants: ['Coco'], votes: 2 },
        { variants: ['Mimi'], votes: 2 },
        { variants: ['Veronique'], votes: 1 },
        { variants: ['Edward'], votes: 1 },
        { variants: ['Ayden'], votes: 1 },
        { variants: ['Ayam'], votes: 1 },
        { variants: ['Carlotta'], votes: 1 },
        { variants: ['Daisy'], votes: 1 },
        { variants: ['Ghida'], votes: 1 },
        { variants: ['Kelvin'], votes: 1 },
        { variants: ["Younger brother (can't remember name)"], votes: 1 },
        { variants: ['John'], votes: 1 },
        { variants: ['Luke'], votes: 1 },
        { variants: ['Pierre'], votes: 1 },
        { variants: ['Jean-Luc’s dad'], votes: 1 },
        { variants: ['Diddy'], votes: 1 },
      ],
    },
    {
      text: 'Name Pierre’s favourite minion',
      answers: [
        { variants: ['Jean-Luc', 'JL'], votes: 3 },
        { variants: ['Kelvin'], votes: 2 },
        { variants: ['Maxime'], votes: 2 },
        { variants: ['Cat'], votes: 1 },
        { variants: ['Soniya'], votes: 1 },
        { variants: ['Bernard'], votes: 1 },
        { variants: ['Jeeeeeeeeerem'], votes: 1 },
      ],
    },
    {
      text: 'Who is taller, Pierre or Jean-Luc?',
      answers: [
        { variants: ['Pierre', 'PW'], votes: 2 },
        { variants: ['Jeanluc'], votes: 1 },
        { variants: ['Neither'], votes: 1 },
        { variants: ['The dad'], votes: 1 },
        { variants: ['Pierre with heels'], votes: 1 },
      ],
    },
    {
      text: "What can you find on Pierre's desk",
      answers: [
        { variants: ['Pens'], votes: 1 },
        { variants: ['Holepunch'], votes: 1 },
        { variants: ['Important documents'], votes: 1 },
        { variants: ['Computer', 'Laptop'], votes: 1 },
        { variants: ['Chewing gum'], votes: 1 },
        { variants: ['Crumbs'], votes: 1 },
        { variants: ['Vitamins'], votes: 1 },
        { variants: ['Unfinished lunch'], votes: 1 },
        { variants: ['Moldy food'], votes: 1 },
        { variants: ['Zyn'], votes: 1 },
        { variants: ['Kelvin'], votes: 1 },
      ],
    },
    {
      text: "What can you find under Pierre's desk",
      answers: [
        { variants: ["Pierre's cute legs", "Pierre's legs"], votes: 3 },
        { variants: ['Crocs'], votes: 2 },
        { variants: ["Pierre's business swimshorts"], votes: 2 },
        { variants: ['Dust'], votes: 1 },
        { variants: ['Slippers'], votes: 1 },
        { variants: ['Sock'], votes: 1 },
        { variants: ['Crumbs'], votes: 1 },
        { variants: ['Banana peel'], votes: 1 },
        { variants: ['Cigarette'], votes: 1 },
        { variants: ['Diapers'], votes: 1 },
        { variants: ['Bibs'], votes: 1 },
        { variants: ['Uwu'], votes: 1 },
        { variants: ['Kelvin'], votes: 1 },
        { variants: ['Baby oil'], votes: 1 },
        { variants: ['JL with puppet strings'], votes: 1 },
      ],
    },
    {
      text: "What is Pierre's favourite task at work",
      answers: [
        { variants: ['Meetings'], votes: 2 },
        { variants: ['Vibe coding', 'Coding'], votes: 2 },
        { variants: ['Eating'], votes: 1 },
        { variants: ['Pulling an all nighter'], votes: 1 },
        { variants: ['Hiring people'], votes: 1 },
        { variants: ['Firing people'], votes: 1 },
        { variants: ['Talk to BM'], votes: 1 },
        { variants: ['Bossing around'], votes: 1 },
        { variants: ['Telling Justin to shut up'], votes: 1 },
        { variants: ['Choosing how much money to make'], votes: 1 },
        { variants: ['Avoiding making eye contact with kelvin'], votes: 1 },
        { variants: ['Do you mean Claude’s favourite task?'], votes: 1 },
        { variants: ['Grabbing the baby oil'], votes: 1 },
      ],
    },
    {
      text: 'Name a hobby Pierre enjoys',
      answers: [
        { variants: ['Sleeping in a toilet before an interview', 'Sleeping in KX loos'], votes: 2 },
        { variants: ['Chess'], votes: 2 },
        { variants: ['$$$', 'Making money'], votes: 2 },
        { variants: ['Fishing'], votes: 1 },
        { variants: ['Making sourdough'], votes: 1 },
        { variants: ['Coffee runs'], votes: 1 },
        { variants: ['Punting'], votes: 1 },
        { variants: ['Rowing'], votes: 1 },
        { variants: ['Cats'], votes: 1 },
        { variants: ['Running'], votes: 1 },
        { variants: ['Football'], votes: 1 },
        { variants: ['Imitating foreign accents'], votes: 1 },
        { variants: ['Gambling'], votes: 1 },
        { variants: ['Lord of the rings marathon'], votes: 1 },
        { variants: ['Bone collecting'], votes: 1 },
        { variants: ['Womanising'], votes: 1 },
        { variants: ['Firing'], votes: 1 },
        { variants: ['Being 30'], votes: 1 },
        { variants: ['Stopping the boats'], votes: 1 },
        { variants: ['Same hobby as JL but a bit better'], votes: 1 },
        { variants: ['Being taller than Jean-Luc'], votes: 1 },
        { variants: ['Giving amazing best man speeches'], votes: 1 },
      ],
    },
    {
      text: 'Is Pierre a good boss?',
      answers: [
        { variants: ['Yes', 'Very yes'], votes: 3 },
        { variants: ['Fuck no', 'No'], votes: 2 },
        { variants: ['Prefer not to say'], votes: 1 },
        { variants: ['When graph go up'], votes: 1 },
        { variants: ['Surprisingly'], votes: 1 },
        {
          variants: [
            'Depends if he had his morning chocolate',
            'Depends on the day',
            'Depends if Ayden is in',
            'Depends on the win',
          ],
          votes: 1,
        },
        { variants: ['The best no fire pls'], votes: 1 },
      ],
    },
    {
      text: 'What is Pierre’s net worth?',
      answers: [
        { variants: ['30m'], votes: 1 },
        { variants: ['50mill gbp'], votes: 1 },
        { variants: ['Depends which currency'], votes: 1 },
        { variants: ['0.1% Nvidia'], votes: 1 },
        { variants: ["1/1000 Elon's"], votes: 1 },
        { variants: ["20x Kelvin's"], votes: 1 },
        { variants: ['1.4x bag ends'], votes: 1 },
        { variants: ['Within the additional rate tax bracker'], votes: 1 },
        { variants: ['More than yours'], votes: 1 },
        { variants: ['1$'], votes: 1 },
        { variants: ['-£17m'], votes: 1 },
        { variants: ['Pierre net is worth the same as other nets'], votes: 1 },
        { variants: ['£12,570 per year'], votes: 1 },
      ],
    },
    {
      text: 'How many properties does Pierre own?',
      answers: [
        { variants: ['1'], votes: 2 },
        { variants: ['2'], votes: 2 },
        { variants: ['3'], votes: 1 },
        { variants: ['7'], votes: 1 },
        { variants: ['Multiple'], votes: 1 },
        { variants: ['More than you'], votes: 1 },
        { variants: ['Mr worldwide 🌍'], votes: 1 },
        { variants: ['Epstein island so 1'], votes: 1 },
        { variants: ['Does Jean-Luc count as Pierre’s property?'], votes: 1 },
      ],
    },
    {
      text: 'How many items of clothing does Pierre own?',
      answers: [
        { variants: ['3'], votes: 1 },
        { variants: ['1 outfit'], votes: 1 },
        { variants: ['No'], votes: 1 },
        { variants: ['Too many 😉'], votes: 1 },
        { variants: ['How many clothes does a homeless man have?'], votes: 1 },
      ],
    },
    {
      text: 'What’s the admin key?',
      answers: [
        { variants: ['password123'], votes: 1 },
        { variants: ['lehigh'], votes: 1 },
        { variants: ['Wsmobile123'], votes: 1 },
      ],
    },
    {
      text: 'Name a famous person named Pierre',
      answers: [
        { variants: ['Pierre Gasly'], votes: 1 },
        { variants: ['Aubameyang'], votes: 1 },
        { variants: ['Pierre Hermé'], votes: 1 },
        { variants: ['Laplace'], votes: 1 },
        { variants: ['Robespierre'], votes: 1 },
        { variants: ['Pierre Laval'], votes: 1 },
        {
          variants: [
            'Pierre Vésiculebiliaire',
            'Pierre Tête-en-L’Air',
            'Pierre Station-Balnéaire',
            'Pierre Alapoclaire',
            'Pierre Calcaire',
            'Pierre Encolère',
          ],
          votes: 1,
        },
        { variants: ['Pierre'], votes: 1 },
      ],
    },
    {
      text: "Who is Pierre's favourite historical figure (alive or dead)",
      answers: [
        { variants: ['Karl Marx'], votes: 1 },
        { variants: ['Chairman Mao'], votes: 1 },
        { variants: ['Genghis Khan'], votes: 1 },
        { variants: ['JD Rockeweller'], votes: 1 },
        { variants: ['Pierre Laval'], votes: 1 },
        { variants: ['Napoleon (Pierre v short)'], votes: 1 },
        { variants: ['Liz Truss'], votes: 1 },
      ],
    },
    {
      text: "What is Pierre's ethnicity",
      answers: [
        { variants: ['Fr*nch', 'French'], votes: 2 },
        { variants: ['British'], votes: 1 },
        { variants: ['White other'], votes: 1 },
        { variants: ['"Other"'], votes: 1 },
        { variants: ['Franco British Persian'], votes: 1 },
        { variants: ['Indian'], votes: 1 },
        { variants: ['African American'], votes: 1 },
        { variants: ['ET'], votes: 1 },
      ],
    },
    {
      text: 'Which country would Pierre like to visit',
      answers: [
        { variants: ['England'], votes: 1 },
        { variants: ['Scotland'], votes: 1 },
        { variants: ['Wales'], votes: 1 },
        { variants: ['Ireland'], votes: 1 },
        { variants: ['Northern Ireland'], votes: 1 },
        { variants: ['Morocco'], votes: 1 },
        { variants: ['Russia'], votes: 1 },
        { variants: ['Middle earth'], votes: 1 },
        { variants: ['Pride'], votes: 1 },
      ],
    },
    {
      text: 'Name an item of footwear Pierre wears on a regular basis',
      answers: [
        { variants: ['Crocs'], votes: 3 },
        { variants: ['High Heels', 'Stilletos'], votes: 2 },
        { variants: ['Shoes'], votes: 1 },
        { variants: ['Flipflops'], votes: 1 },
        { variants: ['Jean-Luc'], votes: 1 },
      ],
    },
    {
      text: "Who is Pierre's best friend",
      answers: [
        { variants: ['Soniya'], votes: 3 },
        { variants: ['JL', 'Jean-Luc'], votes: 2 },
        { variants: ['The cats', 'Cat'], votes: 2 },
        { variants: ['Kelvin'], votes: 1 },
        { variants: ['Charlie Cui'], votes: 1 },
        { variants: ['Alex Benger'], votes: 1 },
        { variants: ['Lilly'], votes: 1 },
        { variants: ['Aydin'], votes: 1 },
        { variants: ['Hard work'], votes: 1 },
        { variants: ['Money'], votes: 1 },
        { variants: ['Gemini 3.1 Pro'], votes: 1 },
        { variants: ['GPT-5.6 Sol'], votes: 1 },
        { variants: ['Claude Sonnet 5'], votes: 1 },
        { variants: ['The office chair'], votes: 1 },
      ],
    },
    {
      text: 'Name Pierre’s fav wag from WSD',
      answers: [
        { variants: ['Ghida'], votes: 2 },
        { variants: ['Kelvin'], votes: 2 },
        { variants: ['Tony'], votes: 1 },
        { variants: ['Sumedha'], votes: 1 },
        { variants: ['Martha'], votes: 1 },
        { variants: ['Solène'], votes: 1 },
        { variants: ['Ellen'], votes: 1 },
        { variants: ['Soniya'], votes: 1 },
        { variants: ['Dany'], votes: 1 },
        { variants: ['Sarah'], votes: 1 },
        { variants: ['Maxime'], votes: 1 },
        { variants: ['Aayam'], votes: 1 },
        { variants: ['Svet (with long hair)'], votes: 1 },
      ],
    },
    {
      text: 'What’s a fun fact about Pierre people might not know?',
      answers: [
        { variants: ['He has a brother'], votes: 1 },
        { variants: ['Worked in a coffee shop'], votes: 1 },
        { variants: ['French'], votes: 1 },
        { variants: ['He hates Joel'], votes: 1 },
        { variants: ['He loves Kelvin'], votes: 1 },
        { variants: ['His favorite person is Ayden'], votes: 1 },
        { variants: ['Anti immigration'], votes: 1 },
        { variants: ['He’s actually taller than JL'], votes: 1 },
        { variants: ['He likes to sleep in public toilets'], votes: 1 },
        { variants: ['Pierre has webbed toes and can swim like a beautiful whale'], votes: 1 },
      ],
    },
    {
      text: 'Who is Pierre firing next',
      answers: [
        { variants: ['Jean-Luc', 'JL', 'Jean luc'], votes: 4 },
        { variants: ['Aydin', 'Ayden'], votes: 4 },
        { variants: ['Kelvin'], votes: 2 },
        { variants: ['Maxime'], votes: 2 },
        { variants: ['Toby'], votes: 1 },
        { variants: ['Sparkles'], votes: 1 },
        { variants: ['Bernard'], votes: 1 },
        { variants: ['One of the HR'], votes: 1 },
        { variants: ['MM'], votes: 1 },
        {
          variants: [
            'If Pierre hires a woman in the next 4 months then her, otherwise most feminine member of current team (Kelvin)',
          ],
          votes: 1,
        },
      ],
    },
    {
      text: 'What’s Pierre’s stripper name?',
      answers: [
        { variants: ['Honey'], votes: 1 },
        { variants: ['Diamond'], votes: 1 },
        { variants: ['Cash'], votes: 1 },
        { variants: ['Roulette'], votes: 1 },
        { variants: ['Blackjack'], votes: 1 },
        { variants: ['Pman'], votes: 1 },
        { variants: ['Big P'], votes: 1 },
        { variants: ['Shyboi'], votes: 1 },
        { variants: ['Pearl Weller'], votes: 1 },
        { variants: ['Pierre with the pair'], votes: 1 },
        { variants: ['Pierre Wellhung', 'Pierre Wellhard'], votes: 1 },
        { variants: ['Kalvin'], votes: 1 },
        { variants: ['Jeanluc'], votes: 1 },
        { variants: ['Jean-Cul'], votes: 1 },
        { variants: ['Jean-Lic'], votes: 1 },
        { variants: ['Jeans-Off'], votes: 1 },
        { variants: ['Taller Jean-Luc'], votes: 1 },
        { variants: ['Galadriel queen of the elves'], votes: 1 },
      ],
    },
    {
      text: 'Wouldn’t it be better if Jean-Luc was boss?',
      answers: [
        { variants: ['Fuckkk no', 'No', 'Very no'], votes: 3 },
        { variants: ['Depends on the day'], votes: 1 },
        { variants: ['If you fancy sleeping'], votes: 1 },
        { variants: ['Jean-Luc pretty much is the boss tbh', 'Yes', '100%'], votes: 1 },
      ],
    },
    {
      text: 'Name a phrase Pierre says all the time',
      answers: [
        { variants: ['CMON', 'Cmon'], votes: 4 },
        { variants: ['For fucks sake'], votes: 1 },
        { variants: ['Fils de pute'], votes: 1 },
        { variants: ['Ogod'], votes: 1 },
        { variants: ['...mate'], votes: 1 },
        { variants: ['Lunch?'], votes: 1 },
        { variants: ['Go away Kelvin'], votes: 1 },
        { variants: ['Kelvin I need your help'], votes: 1 },
        { variants: ["That's a great idea Kelvin"], votes: 1 },
        { variants: ["Kelvin you're promoted"], votes: 1 },
        { variants: ['Ed is the best employee at WSD'], votes: 1 },
        { variants: ['I like big butts and I cannot lie'], votes: 1 },
        { variants: ['I want to be a millionaire so freaking bad'], votes: 1 },
        { variants: ['Adopt an ultra-practical, ultra-fast, ultra-smart mindset'], votes: 1 },
        { variants: ["If my grandmother had wheels she'd be an ev bicycle"], votes: 1 },
        { variants: ['Please applause the winner of the wooden spoon'], votes: 1 },
        { variants: ['Soniya I’m Wellard'], votes: 1 },
        { variants: ['Bad JL!'], votes: 1 },
        { variants: ['Who’s a good JL, here’s another jonnySnack'], votes: 1 },
        { variants: ['I wish I was Jean-Luc'], votes: 1 },
        { variants: ['I’m glad I’m not Jean-Luc'], votes: 1 },
        { variants: ['Jean-Luc makes me Jean-Puc'], votes: 1 },
        { variants: ['Ello stunzo (to mirror)'], votes: 1 },
        { variants: ['Heil Hitler'], votes: 1 },
        { variants: ['Allahu Akbar'], votes: 1 },
        { variants: ['*silence*'], votes: 1 },
      ],
    },
  ],
};
